# Generated by Django 2.1.1 on 2018-09-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player move'), ('S', 'Second player move'),
                                            ('F', 'Game has finished')], default='F', max_length=1),
        ),
    ]
